a={1,2,3,4,5,6,7}
print(a)
print(type(a))
b={"arun","kishore","praveen","punitha","mani"}
print(b)
print(type(b))
names={"abc","edft","grjgiej"}
a.update(names)
print(a)
a.remove("abc")
print(a)
a.discard("jcscu")
print(a)
b.pop()
a.pop()
print(a)
print(b)
a.clear()
print(a)
del b
m={1,2,3,4,5,}
n={"arub","dhfuh","ehufhwew"}
v=m.union(n)
print(v)
m.update(n)
print(m)

r={1,2,3,4,5,6,7,8,9}
p={3,5,6,88,98,6,5,}
t=r.intersection(p)
print(t)
r.update(p)
print(r)
q=r.symmetric_difference(p)
print(q)